const heroV2Css=document.createElement('link');heroV2Css.rel='stylesheet';heroV2Css.href='hero-v2.css';document.head.appendChild(heroV2Css);
const heroV2FixCss=document.createElement('link');heroV2FixCss.rel='stylesheet';heroV2FixCss.href='hero-v2-fix.css';document.head.appendChild(heroV2FixCss);
const section2Css=document.createElement('link');section2Css.rel='stylesheet';section2Css.href='section2.css';document.head.appendChild(section2Css);
const section3Css=document.createElement('link');section3Css.rel='stylesheet';section3Css.href='section3.css';document.head.appendChild(section3Css);
const section4Css=document.createElement('link');section4Css.rel='stylesheet';section4Css.href='section4.css';document.head.appendChild(section4Css);
const hero=document.querySelector('.hero');if(hero){hero.innerHTML=`<div class="hero-v2-shell"><div class="hero-v2-frame"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=2200&q=90" alt="Founder working with finance advisor in a modern office"><div class="hero-v2-nav"><button class="hero-v2-menu" aria-label="Open menu"><span></span></button><a class="hero-v2-brand" href="#top">ARVEN</a><a class="hero-v2-cta" href="#contact">TALK TO AN ADVISOR</a></div><h1 class="hero-v2-title"><span class="hero-v2-title-line">KNOW YOUR</span><span class="hero-v2-title-line">NUMBERS.</span></h1><div class="hero-v2-word-wrap" aria-hidden="true"><div class="hero-v2-word">ARVEN</div></div><span class="hero-v2-side-note">STRATEGIC FINANCE / 2026</span></div></div>`}
const wrapChars=(selector)=>{const el=document.querySelector(selector);if(!el)return;const lines=selector.includes('title')?[...el.querySelectorAll('.hero-v2-title-line')]:[el];let index=0;lines.forEach(line=>{const text=line.textContent;line.textContent='';[...text].forEach(ch=>{const span=document.createElement('span');span.className='char';span.style.setProperty('--i',index++);span.innerHTML=ch===' '?'&nbsp;':ch;line.appendChild(span)})})};wrapChars('.hero-v2-word');wrapChars('.hero-v2-title');
const section2=document.querySelector('.intro');if(section2){section2.classList.add('section2-ref');section2.innerHTML=`<div class="s2-inner"><h2 class="s2-heading">FINANCE, WITH DIRECTION</h2><p class="s2-copy">What worked at $1M in revenue rarely works at $5M. ARVEN helps founders understand the numbers behind their next stage from cash and margins to pricing, hiring, forecasting, and capital so important decisions are made with financial clarity.</p><div class="s2-sticker s2-margin">MARGIN</div><div class="s2-sticker s2-runway">RUNWAY</div><div class="s2-sticker s2-forecast">FORECAST</div></div>`;const heading=section2.querySelector('.s2-heading');let hi=0;const headingText=heading.textContent;heading.textContent='';[...headingText].forEach(ch=>{const span=document.createElement('span');span.className='char';span.style.setProperty('--i',hi++);span.innerHTML=ch===' '?'&nbsp;':ch;heading.appendChild(span)});const copy=section2.querySelector('.s2-copy');const words=copy.textContent.trim().split(/\s+/);copy.textContent='';words.forEach((word,i)=>{const span=document.createElement('span');span.className='word';span.style.setProperty('--i',i);span.textContent=word;copy.appendChild(span);if(i<words.length-1)copy.append(' ')})}
const section3=document.querySelector('.testimonial');if(section3){section3.classList.add('section3-ref');section3.innerHTML=`<div class="s3-inner"><div class="s3-top"><div class="s3-left"><h2 class="s3-title"><span>GROWTH</span><span>GETS</span><span>EXPENSIVE</span></h2><p class="s3-copy">Fast growth can hide weak margins and cash issues. We simplify finances into a clear plan for your team.</p></div><div class="s3-stats"><article class="s3-card"><span class="s3-label">CLIENT REVENUE MODELED</span><strong class="s3-value">$100M+</strong><span class="s3-icon">↗</span></article><article class="s3-card"><span class="s3-label">CAPITAL DECISIONS SUPPORTED</span><strong class="s3-value">$125M+</strong><span class="s3-icon">≋</span></article></div></div></div>`}
const section4=document.querySelector('.services');if(section4){section4.classList.add('section4-ref');section4.innerHTML=`<div class="s4-head"><h2 class="s4-title">WHAT FOUNDERS SAY</h2></div><div class="s4-body"><button class="s4-arrow s4-prev" aria-label="Previous testimonial">◀</button><div class="s4-card-stack"><div class="s4-shadow shadow2"></div><div class="s4-shadow"></div><article class="s4-card"><div class="s4-sticker">CLARITY</div><p class="s4-quote">“We had revenue and a strong team, but made decisions from spreadsheets. ARVEN showed what we could afford and where to change.”</p><div class="s4-author"><div class="s4-avatar"></div><div class="s4-author-text"><strong>MARCUS REED</strong><span>CEO, FIELDSTONE</span></div></div></article></div><button class="s4-arrow s4-next" aria-label="Next testimonial">▶</button></div>`;const t=section4.querySelector('.s4-title');let i=0;const txt=t.textContent;t.textContent='';[...txt].forEach(ch=>{const span=document.createElement('span');span.className='char';span.style.setProperty('--i',i++);span.innerHTML=ch===' '?'&nbsp;':ch;t.appendChild(span)})}
const toggle=document.querySelector('.menu-toggle');const menu=document.querySelector('.site-menu');if(toggle&&menu){toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open?'true':'false')});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}))}
const items=document.querySelectorAll('.reveal,.reveal-scale');const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');io.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -7% 0px'});items.forEach(el=>io.observe(el));
if(section2){const s2Observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-active');s2Observer.unobserve(entry.target)}})},{threshold:.28,rootMargin:'0px 0px -8% 0px'});s2Observer.observe(section2)}
if(section3){const s3Observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-active');s3Observer.unobserve(entry.target)}})},{threshold:.28,rootMargin:'0px 0px -8% 0px'});s3Observer.observe(section3)}
if(section4){const s4Observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-active');s4Observer.unobserve(entry.target)}})},{threshold:.26,rootMargin:'0px 0px -8% 0px'});s4Observer.observe(section4)}
requestAnimationFrame(()=>requestAnimationFrame(()=>document.body.classList.add('is-loaded')));